version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
